### PR TITLE
Updating dependencies + small cleanups

### PR DESCRIPTION
**Pull request by sgomes**
Hello, @mustafa-x and anyone else who might be looking!

I was going through this code over the weekend and giving it a quick cleanup, when I decided I might as well submit the changes back, in case you're interested :)

Hope everything is going well in Google-land!

Cheers,
Sérgio

### CODE REVIEW

**Comment by sgomes** [comment]
I signed it!

**Comment by sgomes** [comment]
Please take another look, @googlebot.

**Comment by mustafa-x** [comment]
Hey @sgomes  want me to merge?

**Comment by sgomes** [comment]
@mustafa-x Yes, please! :)

**Comment by mustafa-x** [comment]
Sorry about the delay @sgomes was out of office :)

**Comment by sgomes** [comment]
No worries at all, thanks for the merge! :D

**Pull request merged**
